[package]
name = "taynik"
version = "1.0.3"
edition = "2021"
description = "Тайник — офлайн-менеджер паролей"
license = "MIT"

build = "src/build.rs"

[dependencies]
gtk4 = "0.9"
glib = "0.20"
rusqlite = { version = "0.32", features = ["bundled"] }
aes-gcm = "0.10"
argon2 = "0.5"
rand = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
zeroize = "1"

[profile.release]
lto = true
strip = true
